export const ANALYTICS_EVENTS = {
  CERTIFICATE_VIEWED: "CERTIFICATE_VIEWED",
  CERTIFICATE_DETAILS: "CERTIFICATE_DETAILS",
  CERTIFICATE_ERROR: "CERTIFICATE_ERROR",
  CERTIFICATE_RENDERER_TIMEOUT: "CERTIFICATE_RENDERER_TIMEOUT",
  CERTIFICATE_PRINT: "CERTIFICATE_PRINT",
  DOCUMENT_VERIFICATION_COMPLETED: "DOCUMENT_VERIFICATION_COMPLETED",
} as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];
